Repository Coinsence/humhub-modules-xcoin, pull requests merged in 2021-09, with the labels that each got.

#116 Tup#283 fix wrong icon in trusted / untrusted btns
  views/challenge/overview.php
  views/marketplace/overview.php
Labels: bug, kredits-1

#120 Tup#315 fix error when non-logged in user clicks on sell your product button in space marketplace
  views/marketplace/overview.php
Labels: bug, kredits-1

#117 Tup#292 make changes to select sender account modal for fundings
  grids/SenderAccountGridView.php
  views/transaction/select-account.php
  widgets/PurchaseCoin.php
  widgets/views/purchase-coin.php
Labels: enhancement, kredits-2

#119 Tup#293 set min amount limit to 10 in purchase coin form
  models/forms/PurchaseForm.php
  views/overview/purchase-coin-prompt.php
Labels: enhancement, kredits-1

#124 TUP#311 - vouchers feature
  controllers/ProductController.php
  migrations/m210902_232241_voucher_table.php
  migrations/m210906_221839_product_voucher.php
  models/Product.php
  models/Voucher.php
  resources/js/xcoin.js
  views/product/details.php
  views/product/edit.php
  views/product/media.php
Labels: kredits-2

#123 Tup#318 filter out unavailable products from user and space profiles
  controllers/MarketplaceController.php
  controllers/ProductController.php
  views/product/details_popup.php
  widgets/MarketplacePortfolio.php
Labels: bug, enhancement, kredits-1

#118 Tup#310 add styles for funding contact buttons
  resources/css/xcoin.css
  resources/css/xcoin.css.map
  resources/less/funding/overview.less
  views/funding/overview.php
Labels: bug, kredits-1

#127 updating voucher feature
  controllers/ProductController.php
  migrations/m210915_215644_remove_is_voucher_product_table.php
  models/Product.php
  resources/js/xcoin.js
  views/product/details.php
  views/product/edit.php
  views/product/media.php
Labels: kredits-2

#126 Tup#317 refactor challenge & marketplace overview layout
  controllers/ChallengeController.php
  controllers/MarketplaceController.php
  resources/css/xcoin.css
  resources/css/xcoin.css.map
  resources/less/miscs.less
  resources/less/templates/overview.less
  resources/less/widgets/social_share.less
  resources/less/xcoin.less
  views/challenge/overview.php
  views/marketplace/overview.php
  widgets/SocialShare.php
  widgets/views/social-share.php
Labels: enhancement, kredits-2

#129 Tup#313 add transfer & invest overview modal step
  controllers/FundingController.php
  controllers/TransactionController.php
  views/funding/invest-overview.php
  views/transaction/transfer-overview.php
Labels: enhancement, kredits-1

#128 Tup#310 refactor funding & product overview pages
  resources/css/xcoin.css
  resources/css/xcoin.css.map
  resources/less/funding/overview.less
  resources/less/templates/co-overview.less
  resources/less/templates/cs-overview.less
  resources/less/widgets/social_share.less
  resources/less/xcoin.less
  views/funding/overview.php
  views/product/overview.php
  widgets/views/marketplace-image.php
Labels: enhancement, kredits-2

#132 Fix purchase coin issue
  views/transaction/select-account.php
Labels: kredits-1

#133 tup #335 : fix error selecting coins
  views/transaction/transfer-select-sender-account.php
Labels: kredits-1
